name: Deploy Javadocs to GitHub Pages

# Run whenever you push to main (or change to your primary branch name)
on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3) Generate Javadoc into target/site/apidocs
      - name: Generate Javadocs
        run: mvn --batch-mode clean javadoc:javadoc

      # 4) Deploy the generated docs to the jvdocs branch
      - name: Deploy to jvdocs branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/apidocs
          publish_branch: jvdocs
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
